### ISSUE TITLE
specs

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/facebook#1]
##### login

Log in with facebook, through:
1. native facebook app.
2. separate browser window in native browser app.

When successful, should set `Facebook.token.val` to `token`.
###### parameters:
- possibly `callback`
###### callback parameters:

If callback is provided, it should be called with the following parameters:
- `error`
- `token`
##### share

Sharing on facebook to own wall or a friend's wall.
###### parameters:
- `url` to share
- preset `text`
- possibly `callback`
###### callback parameters:

If callback is provided, it should be called with the following parameters:
- `error`
- `token`
##### ready

This property is based on the ready event from native, or the SDK initialized on web.
##### token

This property should be managed by the JS API based on the result of the native login method.
##### login

The native side should launch the facebook app if available, otherwise the browser app with the facebook login page etc.
###### parameters:
- callback
###### callback parameters:
- `error`
- `token`
###### parameters:
- `url` to share
- preset `text`
- `callback`
###### callback parameters:
- `error`

**Comment by marcusbesjes** [comment]
@ninjatux do you think is this detailed enough?

**Comment by ninjatux** [comment]
yep, let's ask @avdwerff  and @michielibiza

**Comment by michielibiza** [comment]
Yes, looks detailed enough for now. Since I don't know the facebook sdk by heart I didn't _validate_ what you wrote yet. So perhaps I'll have some questions later when we actually start to implement it...

**Comment by ninjatux** [comment]
@michielibiza will you start this week with Facebook? we were thinking to start from this one since is really simple, there are plenty of examples on the net for requesting oauth tokens and use it in logins

**Comment by michielibiza** [comment]
Indeed there are many examples, are there people in vigour who know a lot about this? can be worthwile to do this at the office on saturday

**Comment by marcusbesjes** [comment]
@michielibiza the facebook SDK documentation is pretty good (e.g. https://developers.facebook.com/docs/facebook-login/android) I was hoping we could get rollin on this sooner :( I understand if you don't have the time because you've told us so every time.. but we have to come up with a way to get the ball rolling with these plugins

**Comment by marcusbesjes** [comment]
I put the specs in the README.md in the root, so closing this

**Comment by michielibiza** [comment]
@marcusbesjes Do we have a facebook app setup for android? If not that's how you can help me by doing that :) I'll have a look if I can do something in the evening this week

**Comment by michielibiza** [comment]
@marcusbesjes @ninjatux 
And next request: can someone setup a test app that uses the facebook plugin? This would save me a _lot_ of time :)

So I would expect:
- a new repo (or merge it into an existing one) 
- that depends on facebook (can be with git in stead of npm, I'll link it locally) and vigour-wrapper
- has `src/index.js` that:
  - gaston will render into a UI
  - requires facebook
  - has some UI element for everything you want to work

**Comment by michielibiza** [comment]
Next question: where do we set the key? options are:
- the js app sends the apikey over the bridge to initialise
- the plugin-build-system gets the key from the app-under-build (then we need to figure out how to keep this secure)
- for this app we hard code the key in the native stuff (then we can't ever make that commit public)
