### ISSUE TITLE
Does not work on TV platform

### ISSUE THREAD

**Issue by DanilloCorvalan** [vigour-io/facebook#15]
I've tested the plugin on tizentv and it doesn't work because this platform runs apps on `file` protocol and I couldn't find a way to setup file protocol on the facebook app settings (allowed domains, web-site url, etc.)

I did a quick research for this problem and one solution is to build the flow manually with https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow and do not use their sdk. Another solution is to authenticate on the server side (that can run in a domain) and return the `token` through an ajax request.

@ninjatux @marcusbesjes @youzi

**Comment by youzi** [comment]
We are going to implement a 2 device login flow (ie use your mobile device to login on tv) for fireTV, which we will implement on all tv's. That means we won't need fb authentication on the tv.

**Comment by ninjatux** [comment]
i closed this issue because it's not an issue :p
