### ISSUE TITLE
[iOS] native login error

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/facebook#16]
"The operation couldn’t be completed. (com.facebook.sdk.login error 308.)"

Get's thrown from native on log in. I've encountered this now when building the SBS app. Running isolated tests now.

**Comment by shawninder** [comment]
@marcusbesjes 308 is a permanent redirect.. Probably the code is expecting a 2*\* response. The fix fill probably be to reach the new URL.. Or if this is native, this probably means getting a newer version of the SDK... Or changing the code so that it follows redirects. This is just a guess though.

**Comment by marcusbesjes** [comment]
@shawninder I'm afraid this is not the HTTP status code 308, but rather a code that is relevant in terms of the facebook SDK.

https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginConstants.h#L74

@avdwerff I'm reading that people report this error when they are calling the login method multiple times. We encountered this before and fixed this issue by making sure the JS side waited with doing a login request until it got back a response from the initial check if a user is logged in at the `init` call. I'm going to check if this is still functioning. 
However, I think we should refactor the iOS native side so that it doesn't trip when JS calls login too many times. What you say?

http://www.basedb.net/Index/detail/id/416245.html

https://codedump.io/share/DonSuueSR5d8/1/why-am-i-getting-comfacebooksdklogin-error-308

**Comment by shawninder** [comment]
ah ok my bad. Carry on :p

**Comment by marcusbesjes** [comment]
I saw that part of the problem was that `facebook.user.val`was not being reset in the case of unsuccessful login, this means that you only had one attempt at facebook login after that you're blocked out.

**Comment by marcusbesjes** [comment]
It looks like this problem is due to mis matching facebook appIds in the build vs the app served, or appId's used that are not "open to the public". Doesn't seem like its a facebook plugin issue.
