### ISSUE TITLE
[build] Build app found in example folder

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/facebook#3]
We need to be able to run native builds from the plugin repo. The app should load the content found in the `example` folder.

We then need instructions in the README file on how to run the builds

**Comment by shawninder** [comment]
This is done but the example app is broken: see https://github.com/vigour-io/facebook/issues/4

**Comment by shawninder** [comment]
@ninjatux I'm going to let you close this when the goal has been acheived

**Comment by ninjatux** [comment]
closing, build works.
