### ISSUE TITLE
[FB] New account for managing test apps

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/facebook#5]
We need a shared account for managing apps used during testing.

**Comment by marcusbesjes** [comment]
login: dev@vigour.io
ask someone for the password

go to https://developers.facebook.com

Every test app can only have one domain tied to it, e.g. `http://192.168.1.23:8081/` for local testing with gaston, but this address might change per local set up. So we need a "test app" for every domain.

To create one, DO NOT create a new app! In stead click on the Vigorous Testing app, and then create a "test app".

![screen shot 2015-11-18 at 11 33 27](https://cloud.githubusercontent.com/assets/3897729/11238916/313ea5dc-8de9-11e5-8713-84e1178f6d86.png)

![screen shot 2015-11-18 at 11 34 04](https://cloud.githubusercontent.com/assets/3897729/11239025/d40c8658-8de9-11e5-8f4e-8b5afb0e69f7.png)

And name it starting with a dash, and then something relevant e.g. `- http://192.168.1.25:8081` if you created it for that domain.

Then you can use dat appId, and log in using the dev@vigour.io facebook account.
